version: "3.7"

services:
  database_cars:
    image: postgres
    container_name: database_cars
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=carsapi
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: carsapi
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - node-network
    links: 
      - database_cars
    depends_on:
      - database_cars

volumes:
  pgdata:
    driver: local

networks:
    node-network:
        driver: bridge