version: "3.9"

services:
  database_cars:
    image: postgres
    container_name: database_cars
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=carsapi
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: carsapi
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database_cars
    depends_on:
      - database_cars

volumes:
  pgdata:
    driver: local
